apiVersion: v1
kind: Service
metadata:
  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /
    # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <arn-of-ssl-cert>
    # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "80"
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotation-policy: "ELBSecurityPolicy-2016-08"
    # external-dns.alpha.kubernetes.io/hostname: <your-custom-domain>
  name: wisecow-service
spec:
  selector:
    app: wisecow-app
    
  ports:
    # - protocol: TCP
    #   port: 443
    #   targetPort: 4499
    - protocol: TCP
      port: 80
      targetPort: 4499

  type: LoadBalancer